
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '773D7DC7AD2229B9E217F987D45D2785'
    
_lr_action_items = {'VIRGULILLA':([0,2,3,5,6,7,9,10,11,19,21,22,23,24,25,26,27,28,],[3,3,-17,-3,-4,-5,-14,-15,-16,-16,-7,-8,-9,-10,-11,-12,-13,-6,]),'$end':([1,2,3,4,5,6,7,9,10,11,19,21,22,23,24,25,26,27,28,],[0,-2,-17,-1,-3,-4,-5,-14,-15,-16,-16,-7,-8,-9,-10,-11,-12,-13,-6,]),'PARABRE':([3,8,12,13,14,15,16,17,20,],[8,8,8,8,8,8,8,8,8,]),'INT':([3,8,12,13,14,15,16,17,20,],[9,9,9,9,9,9,9,9,9,]),'FLOAT':([3,8,12,13,14,15,16,17,20,],[10,10,10,10,10,10,10,10,10,]),'ID':([3,8,12,13,14,15,16,17,20,],[11,19,19,19,19,19,19,19,19,]),'SUMA':([5,9,10,11,18,19,21,22,23,24,25,26,27,28,],[12,-14,-15,-16,12,-16,-7,-8,-9,-10,-11,-12,-13,12,]),'RESTA':([5,9,10,11,18,19,21,22,23,24,25,26,27,28,],[13,-14,-15,-16,13,-16,-7,-8,-9,-10,-11,-12,-13,13,]),'MUL':([5,9,10,11,18,19,21,22,23,24,25,26,27,28,],[14,-14,-15,-16,14,-16,14,14,-9,-10,-11,-12,-13,14,]),'DIV':([5,9,10,11,18,19,21,22,23,24,25,26,27,28,],[15,-14,-15,-16,15,-16,15,15,-9,-10,-11,-12,-13,15,]),'POTEN':([5,9,10,11,18,19,21,22,23,24,25,26,27,28,],[16,-14,-15,-16,16,-16,16,16,16,16,-11,-12,-13,16,]),'MOD':([5,9,10,11,18,19,21,22,23,24,25,26,27,28,],[17,-14,-15,-16,17,-16,17,17,17,17,-11,-12,-13,17,]),'PARCIERRA':([9,10,18,19,21,22,23,24,25,26,27,],[-14,-15,27,-16,-7,-8,-9,-10,-11,-12,-13,]),'IGUAL':([11,],[20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'instrucciones':([0,2,],[1,4,]),'calc':([0,2,],[2,2,]),'expression':([3,8,12,13,14,15,16,17,20,],[5,18,21,22,23,24,25,26,28,]),'var_assing':([3,],[6,]),'empty':([3,],[7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> instrucciones","S'",1,None,None,None),
  ('instrucciones -> calc instrucciones','instrucciones',2,'p_instrucciones_lista','calc.py',85),
  ('instrucciones -> calc','instrucciones',1,'p_instrucciones_lista','calc.py',86),
  ('calc -> VIRGULILLA expression','calc',2,'p_calc','calc.py',90),
  ('calc -> VIRGULILLA var_assing','calc',2,'p_calc','calc.py',91),
  ('calc -> VIRGULILLA empty','calc',2,'p_calc','calc.py',92),
  ('var_assing -> ID IGUAL expression','var_assing',3,'p_var_assing','calc.py',98),
  ('expression -> expression SUMA expression','expression',3,'p_expression','calc.py',105),
  ('expression -> expression RESTA expression','expression',3,'p_expression','calc.py',106),
  ('expression -> expression MUL expression','expression',3,'p_expression','calc.py',107),
  ('expression -> expression DIV expression','expression',3,'p_expression','calc.py',108),
  ('expression -> expression POTEN expression','expression',3,'p_expression','calc.py',109),
  ('expression -> expression MOD expression','expression',3,'p_expression','calc.py',110),
  ('expression -> PARABRE expression PARCIERRA','expression',3,'p_expression_par','calc.py',116),
  ('expression -> INT','expression',1,'p_expression_int_float','calc.py',123),
  ('expression -> FLOAT','expression',1,'p_expression_int_float','calc.py',124),
  ('expression -> ID','expression',1,'p_expression_var','calc.py',130),
  ('empty -> <empty>','empty',0,'p_empty','calc.py',140),
]
